root = "."
tmp_dir = ".tmp/dev/air/chat"

[build]
cmd = "go build -o .tmp/dev/bin/chat ./cmd/chat"
bin = ".tmp/dev/bin/chat"
delay = 300
include_ext = ["go", "tpl", "tmpl", "html", "sql", "yaml", "yml", "json"]
exclude_dir = [".git", ".tmp", "api/gen", "data"]

[log]
time = true

[misc]
clean_on_exit = true
