root = "."
tmp_dir = ".tmp/dev/air/userhub"

[build]
cmd = "go build -o .tmp/dev/bin/userhub ./cmd/userhub"
bin = ".tmp/dev/bin/userhub"
delay = 300
include_ext = ["go", "tpl", "tmpl", "html", "sql", "yaml", "yml", "json"]
exclude_dir = [".git", ".tmp", "api/gen", "data"]

[log]
time = true

[misc]
clean_on_exit = true
